### ISSUE TITLE
[Phase 1] GitHub - CI/CD Workflow Setup

### ISSUE THREAD

**Issue by admarble** [admarble/Vidst#43]
## Objective
Set up GitHub Actions workflows for automated testing and deployment.

### Timeline
- Start: Feb 2, 2025
- Target: Feb 4, 2025

### Implementation Details
1. Create basic test workflow:
```yaml
# .github/workflows/tests.yml
name: Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m pytest
```

2. Configure Dependabot:
```yaml
# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    versioning-strategy: "lockfile-only"
```

3. Set up PR template:
```markdown
## Description
Brief description of changes

## Type of Change
- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update

## Testing
- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] All tests passing

## Documentation
- [ ] Documentation updated
- [ ] Code comments added/updated

## Related Issues
Fixes # (issue)
```

4. Configure coverage reporting:
- Set up pytest-cov
- Configure coverage thresholds
- Set up coverage reporting in PRs

### Technical Requirements
- GitHub Actions configuration
- Dependabot setup
- PR template setup
- Test automation
- Coverage reporting

### Definition of Done
- [ ] Test workflow implemented and tested
- [ ] Dependabot configured
- [ ] PR template created
- [ ] Coverage reporting working
- [ ] Documentation updated
- [ ] All checks passing in test PR

### Related Documentation
- See `GitHub Setup Guide - Video Understanding AI PoC.md`
